### ISSUE TITLE
[Remodifer][1.18.2] Crash when applying modifiers with non-vanilla attributes?

### ISSUE THREAD

**Issue by Thombias** [MCTeamPotato/Kasualix-Issue-Tracker#88] opened 2023-10-08 15:28 UTC
Hi there! i've recently been configuring remodifier to fit my needs for my modpack but i believe the mod doesn't seem to like modded attributes very much. Just now i made a test world and gave myself some armors, they exclusively use only vanilla attributes so no issues there, everything works as it should.

But for tools i am using forge:reach_distance and forge:attack_range in addition to vanilla attributes because i want more diverse modifers than just being stuck with attack damage and attack speed. On the same test world i gave myself 3 tools where 2 of them applied modifers with vanilla attributes but i think the 3rd tool happened to apply one with the 2 forge attributes and immediately caused a crash as soon as i tried holding the tool in my hand and letting the mod apply the modifier.

I also encountered another issue with a modded attribute, i'm using this mod https://www.curseforge.com/minecraft/mc-mods/projectile-damage-attribute in hopes of bows being able to get damage modifers as well, but unfortunately they don't seem to work. Attempting to apply them to a bow makes the name of the modifier pop up in the item name like "Unreal Bow", but in the tooltip nothing shows up. Testing out the damage output i also didn't see any difference, even with very extreme values like +10 projectile damage from the modifier.

Is this a bug and can it be fixed?

I'll put in the crash log right here for the modded attribute issue:
[crash-2023-10-08_16.58.21-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12841030/crash-2023-10-08_16.58.21-server.txt)

Minecraft version: 1.18.2
Forge version: 40.2.10
Mod version: 2.0.4

**Comment by CCCClear** [comment] 2023-11-13 10:42
The same issue

**Comment by Thombias** [comment] 2023-11-15 22:01
I just tried v2.2.0 but unfortunately the issue still persists. Can apply modifers with vanilla attributes, as soon as a modifier with non-vanilla attributes tries to apply to a tool it crashes. I triple checked if the attributes are defined correctly in the .toml and they are, not sure why it says they are "null" in the crash report. :/
I'll leave my tool-modifiers.toml file as well as the crash-report here so anyone can take a look and try it out for themselves.
[tool-modifers_config.zip](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13369987/tool-modifers_config.zip)
[crash-2023-11-15_22.50.30-server.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/13370008/crash-2023-11-15_22.50.30-server.txt)

**Comment by Kasualix** [comment] 2023-11-16 04:07
seems to be a 1.18.2 specific issue as I cannot reproduce it on 1192

**Comment by Kasualix** [comment] 2024-02-02 16:30
Fixed [here](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/issues/117#issuecomment-1923808036), new versions will be released soon

**Closed by Kasualix** 2024-02-02 16:30 UTC
