### ISSUE TITLE
Redirectionor prevents you from going to hell.

### ISSUE THREAD

**Issue by ForestLive6** [MCTeamPotato/Kasualix-Issue-Tracker#8] opened 2023-07-12 11:55 UTC
Redirectionor prevents you from going to hell.
If this mod is installed on the server, it is impossible to enter hell. When loading hell, just throws out of the server. When uninstalling the mod, such a problem is not observed. 
Version Redirectionor redirectionor-1.16.5-1.2.1.jar
Can this happen because of the fact that installed Opotato which fixes DEUF? So there is a conflict because of class distribution? This is purely my thoughts and assumption.

I attach two videos below for clarity: 
Redirectionor mod installed on the server
https://youtu.be/XFfWJtszQBA

Redirectionor mod removed from the server
https://youtu.be/lAy7WxY4stU

**Comment by Kasualix** [comment] 2023-07-12 13:57
Can you send the latest logs in the serverside and clientside?

**Comment by ForestLive6** [comment] 2023-07-12 14:11
> Can you send the latest logs in the serverside and clientside?

Yeah, I'll send it out shortly.

**Comment by ForestLive6** [comment] 2023-07-12 14:20
> Can you send the latest logs in the serverside and clientside?

Latest server:
[latest server.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12028902/latest.server.log)

Latest client:
[latest client.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12028905/latest.client.log)

**Comment by Kasualix** [comment] 2023-07-12 23:58
Did the server generate a crash report?

**Comment by Kasualix** [comment] 2023-07-13 03:34
This may be a mod incompatibility as I can't reproduce it in my pack with redirectionor

**Comment by Kasualix** [comment] 2023-07-13 03:43
I found it, [this ~buggy MCreator~ mod](https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii) may be doing some unexpected things.

**Comment by Kasualix** [comment] 2023-07-13 05:58
MCreator mods codes are so terrible.
I'll add incompat note on CurseForge.

**Comment by ForestLive6** [comment] 2023-07-13 09:55
Hi, crash report is not created, when going to hell, it writes an error in the console, but for some reason it doesn't go to latest. 
I attach the error I copied from the console.  
[Console.txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12038009/Console.txt)

**Comment by ForestLive6** [comment] 2023-07-13 10:31
Having removed the mod The Abyss II, the error remained, also crashes when I go to hell.

**Comment by Kasualix** [comment] 2023-07-13 10:38
send new log pls, valid info is always needed.
My test env was very clear. Abyss II and my mod, once remove one of them, I can enter the nether successfully.

**Comment by ForestLive6** [comment] 2023-07-13 10:42
Log without The Abyss II mod.
[Log without The Abyss II mod..txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12038456/Log.without.The.Abyss.II.mod.txt)

**Comment by Kasualix** [comment] 2023-07-13 10:45
Can you determine the minimum set of mods necessary to reproduce this crash?

**Comment by ForestLive6** [comment] 2023-07-13 10:46
This is the complete latest where The Abyss mod is removed from the server. 
[latest.log](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12038468/latest.log)

**Comment by ForestLive6** [comment] 2023-07-13 10:47
> Can you determine the minimum set of mods necessary to reproduce this crash?

I will try to do it, but for some reason, with the same collection of mods, on the client such a problem is not. But on the server it is observed.

**Comment by ForestLive6** [comment] 2023-07-13 11:01
I don't know how, but with the version redirectionor-1.16.5-1.1.1.1.jar if it is installed on the server, there is no such problem. Even if redirectionor-1.16.5-1.2.1.jar is installed on the client.

**Comment by Kasualix** [comment] 2023-07-13 11:23
https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/releases/download/1/redirectionor-1.16.5-1.2.1.jar
Can you try this build? I deleted some patches I have added and it went well in my test

**Comment by ForestLive6** [comment] 2023-07-13 11:40
The Abyss II mod is installed.

> https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/releases/download/1/redirectionor-1.16.5-1.2.1.jar Can you try this build? I remo
[The Abyss II mod is installed..txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12038939/The.Abyss.II.mod.is.installed.txt)
ved some patches that I suspected and it went well in my test with TheAbyss

**Comment by ForestLive6** [comment] 2023-07-13 11:40
> https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/releases/download/1/redirectionor-1.16.5-1.2.1.jar Can you try this build? I removed some patches that I suspected and it went well in my test with TheAbyss
The Abyss II mod is installed.
[The Abyss II mod is installed..txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12038949/The.Abyss.II.mod.is.installed.txt)

**Comment by ForestLive6** [comment] 2023-07-13 11:41
The Abyss II mod is installed. 
[The Abyss II mod is installed..txt](https://github.com/MCTeamPotato/Kasualix-Issue-Tracker/files/12038952/The.Abyss.II.mod.is.installed.txt)

**Comment by Kasualix** [comment] 2023-07-14 00:09
Can you try to remove FerriteCore?

**Comment by Kasualix** [comment] 2023-07-14 00:09
Can you try to remove FerriteCore?

**Comment by Kasualix** [comment] 2023-07-14 01:02
How strange
With the same mod set, I cannot get this crash anymore like yesterday

**Comment by Kasualix** [comment] 2023-07-23 18:41
Hoepfully will be resolved in the next version.
I will refactor the mod with architectury loom for multiple platforms support on 1.16.5, just like the 1.18+

**Closed** 2023-08-04 06:01 UTC
